# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Projects/Kintex7_Project/OLED/OLED.srcs/sources_1/ip/rom_picture/rom_picture.xci
# IP: The module: 'rom_picture' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Projects/Kintex7_Project/OLED/OLED.srcs/sources_1/ip/rom_picture/rom_picture_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_picture'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/Projects/Kintex7_Project/OLED/OLED.srcs/sources_1/ip/rom_picture/rom_picture.xci
# IP: The module: 'rom_picture' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Projects/Kintex7_Project/OLED/OLED.srcs/sources_1/ip/rom_picture/rom_picture_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_picture'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
